import os
import sys
import pygame
import requests 

sys.path.insert(0, os.path.dirname(__file__))

# URL API POST Requrst
API_ENDPOINT = "{YOUR_URL}/PyTicTacToe3D/get.php"
  
# Define function
def Send_GET(): 
    data = {} 
    r = requests.post(url = API_ENDPOINT, data = data) 
    #print ("[Request]: Received: {" + str(r.text) + "}")
    return r.text

def application(environ, start_response):
    start_response('200 OK', [('Content-Type', 'text/html')])
    message = '<hr>This code was generated by using: \n'
    version = 'Python %s\n' % sys.version.split()[0]
    response = '\n'.join([Send_GET(), message, version])
    return [response.encode()]
